version: '3.7'
services:
  apirest:
    container_name: desafiolatam-container
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
     - "8080:8080"
    volumes:
     - ./:/usr/src/app  
    command: bash
